# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 610)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 220, 141, 31))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 141, 161))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 20, 132, 134))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout.addWidget(self.radioButton_6)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(20, 190, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 260, 141, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 81))
        self.label.setObjectName("label")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(170, 20, 731, 531))
        self.groupBox_4.setObjectName("groupBox_4")
        self.MplWidget = MplWidget(self.groupBox_4)
        self.MplWidget.setGeometry(QtCore.QRect(10, 20, 711, 501))
        self.MplWidget.setObjectName("MplWidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(19, 379, 141, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableView = QtWidgets.QTableView(self.groupBox_3)
        self.tableView.setGeometry(QtCore.QRect(10, 20, 121, 131))
        self.tableView.setObjectName("tableView")
        self.groupBox_4.raise_()
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.comboBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.groupBox.setTitle(_translate("MainWindow", "Type of map:"))
        self.radioButton.setText(_translate("MainWindow", "Network layout"))
        self.radioButton_2.setText(_translate("MainWindow", "Undirected AC"))
        self.radioButton_3.setText(_translate("MainWindow", "Directed AC"))
        self.radioButton_4.setText(_translate("MainWindow", "Weighted AC"))
        self.radioButton_5.setText(_translate("MainWindow", "Mixed AC"))
        self.radioButton_6.setText(_translate("MainWindow", "Betweenness"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Test net"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Hanoi Network"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Two-loop Network"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Two-reservoir Network"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Exeter Network"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Fossolo Network"))
        self.comboBox.setItemText(6, _translate("MainWindow", "GoYang Network"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Modena Network"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Zijin Network"))
        self.comboBox.setItemText(9, _translate("MainWindow", "New York Tunnel Network"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Pescara Network"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Rural network"))
        self.comboBox.setItemText(12, _translate("MainWindow", "testcase_1"))
        self.comboBox.setItemText(13, _translate("MainWindow", "testcase_2"))
        self.comboBox.setItemText(14, _translate("MainWindow", "testcase_3"))
        self.comboBox.setItemText(15, _translate("MainWindow", "testcase_4"))
        self.comboBox.setItemText(16, _translate("MainWindow", "testcase_5"))
        self.groupBox_2.setTitle(_translate("MainWindow", "General information:"))
        self.label.setText(_translate("MainWindow", "None"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Network map:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Component information"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))

from mplwidget import MplWidget
